In [1]:
import sys
sys.path.append("../../")

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../../data/europe.csv", delimiter=',', encoding='utf-8')
df

,Country,Area,GDP,Inflation,Life.expect,Military,Pop.growth,Unemployment
0,Austria,83871,41600,3.5,79.91,0.80,0.03,4.2
1,Belgium,30528,37800,3.5,79.65,1.30,0.06,7.2
2,Bulgaria,110879,13800,4.2,73.84,2.60,-0.80,9.6
3,Croatia,56594,18000,2.3,75.99,2.39,-0.09,17.7
4,Czech Republic,78867,27100,1.9,77.38,1.15,-0.13,8.5
5,Denmark,43094,37000,2.8,78.78,1.30,0.24,6.1
6,Estonia,45228,20400,5.0,73.58,2.00,-0.65,12.5
7,Finland,338145,36000,3.3,79.41,2.00,0.07,7.8
8,Germany,357022,38100,2.5,80.19,1.50,-0.20,6.0
9,Greece,131957,26300,3.3,80.05,4.30,0.06,17.4
10,Hungary,93028,19600,3.9,75.02,1.75,-0.18,10.9
11,Iceland,103000,38100,4.0,81.00,0.00,0.67,7.4
12,Ireland,70273,40800,2.6,80.32,0.90,1.11,14.4
13,Italy,301340,30500,2.9,81.86,1.80,0.38,8.4
14,Latvia,64589,16800,4.4,72.93,1.10,-0.60,12.8
15,Lithuania,65300,19100,4.1,75.55,0.90,-0.28,15.4
16,Luxembourg,2586,80600,3.4,79.75,0.90,1.14,5.7
17,Netherlands,41543,42000,2.3,80.91,1.60,0.45,4.4
18,Norway,323802,53400,1.3,80.32,1.90,0.33,3.3
19,Poland,312685,20200,4.2,76.25,1.90,-0.08,12.4
20,Portugal,92090,23400,3.7,78.70,2.30,0.18,12.7
21,Slovakia,49035,23300,3.9,76.03,1.08,0.10,13.2
22,Slovenia,20273,28800,1.8,77.48,1.70,-0.19,11.8
23,Spain,505370,30500,3.1,81.27,1.20,0.65,21.7
24,Sweden,450295,40700,3.0,81.18,1.50,0.17,7.5
25,Switzerland,41277,44500,0.2,81.17,1.00,0.92,2.8
26,Ukraine,603550,7200,8.0,68.74,1.40,-0.63,7.9
27,United Kingdom,243610,36500,4.5,80.17,2.70,0.55,8.1

In [4]:
to_normalize = ["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]
for i in range(len(to_normalize)):
    df[to_normalize[i]] = (df[to_normalize[i]] - df[to_normalize[i]].mean()) / df[to_normalize[i]].std()
df

,Country,Area,GDP,Inflation,Life.expect,Military,Pop.growth,Unemployment
0,Austria,-0.498684,0.671577,0.112385,0.560493,-1.005889,-0.173603,-1.223084
1,Belgium,-0.820923,0.409546,0.112385,0.478967,-0.381944,-0.113838,-0.581766
2,Bulgaria,-0.335532,-1.245385,0.613007,-1.342832,1.240314,-1.827104,-0.068713
3,Croatia,-0.663461,-0.955772,-0.745825,-0.668672,0.978257,-0.412664,1.662844
4,Czech Republic,-0.528913,-0.328277,-1.031894,-0.232820,-0.569127,-0.492350,-0.303862
5,Denmark,-0.745013,0.354382,-0.388238,0.206167,-0.381944,0.244752,-0.816916
6,Estonia,-0.732122,-0.790279,1.185146,-1.424358,0.491580,-1.528278,0.551227
7,Finland,1.037356,0.285426,-0.030650,0.403712,0.491580,-0.093917,-0.453503
8,Germany,1.151389,0.430233,-0.602790,0.648291,-0.132366,-0.631802,-0.838293
9,Greece,-0.208202,-0.383442,-0.030650,0.604392,3.361728,-0.113838,1.598712
10,Hungary,-0.443368,-0.845443,0.398454,-0.972828,0.179607,-0.591959,0.209192
11,Iceland,-0.383128,0.430233,0.469972,0.902276,-2.004201,1.101385,-0.539012
12,Ireland,-0.580828,0.616413,-0.531272,0.689054,-0.881100,1.977939,0.957395
13,Italy,0.815021,-0.093829,-0.316720,1.171940,0.242002,0.523656,-0.325239
14,Latvia,-0.615165,-1.038518,0.756041,-1.628174,-0.631522,-1.428670,0.615359
15,Lithuania,-0.610870,-0.879921,0.541489,-0.806640,-0.881100,-0.791176,1.171167
16,Luxembourg,-0.989718,3.360840,0.040867,0.510323,-0.881100,2.037704,-0.902425
17,Netherlands,-0.754383,0.699159,-0.745825,0.874056,-0.007576,0.663108,-1.180329
18,Norway,0.950711,1.485251,-1.460999,0.689054,0.366791,0.424047,-1.415479
19,Poland,0.883555,-0.804070,0.613007,-0.587146,0.366791,-0.392742,0.529850
20,Portugal,-0.449034,-0.583412,0.255419,0.181082,0.865947,0.125222,0.593982
21,Slovakia,-0.709125,-0.590308,0.398454,-0.656130,-0.656480,-0.034151,0.700868
22,Slovenia,-0.882872,-0.211053,-1.103412,-0.201464,0.117213,-0.611880,0.401587
23,Spain,2.047542,-0.093829,-0.173685,0.986938,-0.506733,1.061541,2.517934
24,Sweden,1.714841,0.609517,-0.245203,0.958718,-0.132366,0.105300,-0.517635
25,Switzerland,-0.755990,0.871548,-2.247691,0.955582,-0.756311,1.599427,-1.522365
26,Ukraine,2.640636,-1.700491,3.330669,-2.942001,-0.257155,-1.488435,-0.432126
27,United Kingdom,0.466281,0.319904,0.827559,0.642019,1.365103,0.862325,-0.389371

In [5]:
from utils.kohonen.kohonen import build_kohonen_net
from utils.kohonen.neuron_neighbours import prop2iters_neighbour_radius
from utils.kohonen.neuron_lr import inv2iter_learning_rate

In [6]:
kohonen_net = build_kohonen_net(df[["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]], 2, 7*500, 
                                "sample no repos", "stochastic", 
                                prop2iters_neighbour_radius, inv2iter_learning_rate, 
                                "rectangular")

In [7]:
austria = df[["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]].iloc[0].to_numpy()
switzerland = df[["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]].iloc[25].to_numpy()
luxemburg = df[["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]].iloc[16].to_numpy()

greece = df[["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]].iloc[9].to_numpy()
hungary = df[["Area", "GDP", "Inflation", "Life.expect", "Military", "Pop.growth", "Unemployment"]].iloc[10].to_numpy()

In [8]:
kohonen_net.predict(austria)

(0, 0)

In [9]:
kohonen_net.predict(switzerland)

(0, 0)

In [10]:
kohonen_net.predict(luxemburg)

(0, 0)

In [11]:
kohonen_net.predict(greece)

(1, 1)

In [12]:
kohonen_net.predict(hungary)

(1, 1)